# Todo App — State Store Components
# Apply: kubectl apply -f todo-app-statestore-example.yaml

---
# Redis state store for local development (conversation cache, rate limiting)
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis-master.default.svc.cluster.local:6379"
    - name: redisPassword
      value: ""
    - name: keyPrefix
      value: "name"
    - name: actorStateStore
      value: "false"
  scopes:
    - backend-api
    - mcp-server

---
# PostgreSQL state store for production (Neon Serverless)
# Uncomment and replace Redis above for production deployments.
#
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: statestore
#   namespace: default
# spec:
#   type: state.postgresql.v2
#   version: v1
#   metadata:
#     - name: connectionString
#       secretKeyRef:
#         name: db-credentials
#         key: connection-string
#     - name: tableName
#       value: "dapr_state"
#     - name: cleanupInterval
#       value: "3600"
#     - name: maxConns
#       value: "5"
#   scopes:
#     - backend-api
#     - mcp-server
# auth:
#   secretStore: kubernetes

---
# Cron binding: check overdue tasks every 5 minutes
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-overdue-check
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 5m"
    - name: direction
      value: "input"
  scopes:
    - backend-api

---
# Cron binding: process recurring tasks every hour
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-recurring-tasks
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 1h"
    - name: direction
      value: "input"
  scopes:
    - backend-api
