apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-overdue-check
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 5m"
    - name: route
      value: "/cron-overdue-check"
scopes:
  - backend-api
