# Full CI/CD Pipeline Example for hackathon-todo
# Place at: .github/workflows/cicd.yaml
#
# This is a complete, single-file CI/CD pipeline that:
# 1. Runs tests on every PR
# 2. Builds Docker images on push to main
# 3. Deploys to staging automatically
# 4. Deploys to production on manual trigger
#
# Required GitHub Secrets:
#   DIGITALOCEAN_ACCESS_TOKEN
#   DATABASE_URL (for tests)

name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "Deploy to environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository }}
  CLUSTER_NAME: hackathon-todo
  HELM_CHART: deploy/helm/hackathon-todo

permissions:
  contents: read
  packages: write

# ============================================================
# JOB 1: Lint and Test
# ============================================================
jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx

      - name: Run tests
        working-directory: backend
        run: pytest tests/ -v
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ENVIRONMENT: test

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint
        working-directory: frontend
        run: npm run lint

      - name: Type check
        working-directory: frontend
        run: npx tsc --noEmit

  # ============================================================
  # JOB 2: Build Docker Images
  # ============================================================
  build:
    name: Build Images
    needs: [test-backend, test-frontend]
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: frontend
            dockerfile: deploy/docker/frontend/Dockerfile
          - name: backend
            dockerfile: deploy/docker/backend/Dockerfile
          - name: mcp-server
            dockerfile: deploy/docker/mcp-server/Dockerfile
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}/${{ matrix.service.name }}
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ============================================================
  # JOB 3: Deploy to Staging
  # ============================================================
  deploy-staging:
    name: Deploy Staging
    needs: build
    if: >
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_env == 'staging')
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configure kubectl
        run: doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy
        run: |
          IMAGE_TAG="sha-$(echo ${{ github.sha }} | cut -c1-7)"
          helm upgrade --install hackathon-todo ${{ env.HELM_CHART }} \
            -f ${{ env.HELM_CHART }}/values-staging.yaml \
            --namespace staging --create-namespace \
            --set frontend.image.tag=$IMAGE_TAG \
            --set backend.image.tag=$IMAGE_TAG \
            --set mcpServer.image.tag=$IMAGE_TAG \
            --wait --timeout 5m

      - name: Verify
        run: |
          kubectl rollout status deployment/frontend -n staging --timeout=120s
          kubectl rollout status deployment/backend -n staging --timeout=120s
          kubectl get pods -n staging

  # ============================================================
  # JOB 4: Deploy to Production (manual only)
  # ============================================================
  deploy-production:
    name: Deploy Production
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_env == 'production'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configure kubectl
        run: doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Capture pre-deploy state
        run: |
          echo "--- Current release ---"
          helm history hackathon-todo -n production --max 3 || true
          echo "--- Current pods ---"
          kubectl get pods -n production || true

      - name: Deploy
        run: |
          IMAGE_TAG="sha-$(echo ${{ github.sha }} | cut -c1-7)"
          helm upgrade --install hackathon-todo ${{ env.HELM_CHART }} \
            -f ${{ env.HELM_CHART }}/values-production.yaml \
            --namespace production --create-namespace \
            --set frontend.image.tag=$IMAGE_TAG \
            --set backend.image.tag=$IMAGE_TAG \
            --set mcpServer.image.tag=$IMAGE_TAG \
            --wait --timeout 10m

      - name: Verify
        run: |
          kubectl rollout status deployment/frontend -n production --timeout=180s
          kubectl rollout status deployment/backend -n production --timeout=180s
          kubectl rollout status deployment/mcp-server -n production --timeout=180s
          echo "=== All pods ==="
          kubectl get pods -n production
          echo "=== Ingress ==="
          kubectl get ingress -n production

      - name: Post-deploy smoke test
        run: |
          kubectl run smoke-test --rm -i --restart=Never \
            --image=curlimages/curl:latest -n production -- \
            curl -sf http://backend:8000/api/health
          echo "Smoke test passed"

  # ============================================================
  # JOB 5: Auto-rollback on Production Failure
  # ============================================================
  rollback:
    name: Rollback Production
    needs: deploy-production
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configure kubectl
        run: doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Execute rollback
        run: |
          echo "Production deployment failed! Rolling back..."
          helm rollback hackathon-todo -n production
          kubectl get pods -n production
          echo "Rollback complete"
