apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: reminders-sub
spec:
  pubsubname: pubsub
  topic: reminders
  routes:
    default: /events/reminder
  deadLetterTopic: reminders-deadletter
scopes:
  - notification-svc
