apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-updates-sub
spec:
  pubsubname: pubsub
  topic: task-updates
  routes:
    default: /events/task-updates
  deadLetterTopic: task-updates-deadletter
scopes:
  - sse-gateway
