apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-events-sub
spec:
  pubsubname: pubsub
  topic: task-events
  routes:
    default: /events/task
  deadLetterTopic: task-events-deadletter
scopes:
  - backend-api
  - notification-svc
  - mcp-server
