{{- if and .Values.backend.enabled .Values.backend.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.backend.fullname" . }}-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    {{- include "todo-app.backend.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
